Repository 1oT-Itty/itty-spring-backend, pull requests merged in 2024-04, with the labels that each got.

#45 Feat: "CORS 설정"
  itty-backend/src/main/java/org/iot/itty/config/WebConfig.java
Labels: good first issue

#47 [Feat] 유저 정보 수정
  itty-backend/build.gradle
  itty-backend/src/main/java/org/iot/itty/user/controller/UserController.java
  itty-backend/src/main/java/org/iot/itty/user/service/UserService.java
  itty-backend/src/main/java/org/iot/itty/user/service/UserServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/user/vo/RequestUser.java
  itty-backend/src/main/java/org/iot/itty/user/vo/RequestUserModify.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseUserModify.java
  itty-backend/src/main/resources/application.yml
  itty-backend/src/test/java/org/iot/itty/user/controller/UserControllerTests.java
Labels: enhancement

#50 [Feature/article-connect-replies] 자유게시판 CRUD 완료
  .idea/.name
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/itty.main.iml
  .idea/uiDesigner.xml
  itty-backend/.gitignore
  itty-backend/build.gradle
  itty-backend/src/main/java/org/iot/itty/article/aggregate/ArticleEntity.java
  itty-backend/src/main/java/org/iot/itty/article/aggregate/LikeEntity.java
  itty-backend/src/main/java/org/iot/itty/article/controller/ArticleController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/ReplyController.java
  itty-backend/src/main/java/org/iot/itty/article/repository/ReplyRepository.java
  itty-backend/src/main/java/org/iot/itty/article/service/ArticleService.java
  itty-backend/src/main/java/org/iot/itty/article/service/ArticleServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/service/ReplyService.java
  itty-backend/src/main/java/org/iot/itty/article/service/ReplyServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestDeleteFreeBoardArticle.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestModifyFreeBoardArticle.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestRegistFreeBoardArticle.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseDeleteFreeBoardArticle.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseModifyFreeBoardArticle.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseRegistFreeBoardArticle.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseSelectReplyByArticleCodeFk.java
  itty-backend/src/main/java/org/iot/itty/user/controller/UserController.java
  itty-backend/src/main/java/org/iot/itty/user/repository/UserRepository.java
  itty-backend/src/main/java/org/iot/itty/user/service/UserService.java
  itty-backend/src/main/java/org/iot/itty/user/service/UserServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/user/vo/RequestUser.java
  itty-backend/src/main/java/org/iot/itty/user/vo/RequestUserModify.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseUser.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseUserModify.java
  itty-backend/src/main/resources/application.yml
  itty-backend/src/test/java/org/iot/itty/user/controller/UserControllerTests.java
Labels: enhancement

#54 [Feat] 회원별 좋아요 누른 댓글 목록 조회 기능 구현
  itty-backend/src/main/java/org/iot/itty/article/controller/LikeController.java
  itty-backend/src/main/java/org/iot/itty/article/repository/LikeRepository.java
  itty-backend/src/main/java/org/iot/itty/article/service/LikeService.java
  itty-backend/src/main/java/org/iot/itty/article/service/LikeServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseSelectAllLikeByUserCodeFk.java
Labels: enhancement

#55 [Refactor] 회원별 좋아요 누른 댓글 조회 기능 코드 리팩토링
  itty-backend/src/main/java/org/iot/itty/article/controller/LikeController.java
  itty-backend/src/main/java/org/iot/itty/article/service/LikeService.java
  itty-backend/src/main/java/org/iot/itty/article/service/LikeServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseSelectAllLikeByUserCodeFk.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseSelectAllReplyLikedByUserCodeFk.java
Labels: enhancement

#58 [Feat] 자유게시판 전체 조회
  itty-backend/src/main/java/org/iot/itty/article/controller/ArticleController.java
  itty-backend/src/test/java/org/iot/itty/article/controller/ArticleControllerTests.java
  itty-backend/src/test/java/org/iot/itty/article/controller/ReplyControllerTests.java
Labels: enhancement

#59 [Merge] Article Branch Merge
  itty-backend/src/main/java/org/iot/itty/article/controller/ArticleController.java
  itty-backend/src/test/java/org/iot/itty/article/controller/ArticleControllerTests.java
  itty-backend/src/test/java/org/iot/itty/article/controller/ReplyControllerTests.java
Labels: enhancement

#61 [Feat] 자유게시글 테스트
  itty-backend/src/main/java/org/iot/itty/article/controller/ArticleController.java
  itty-backend/src/test/java/org/iot/itty/article/controller/ArticleControllerTests.java
Labels: enhancement

#63 [merge] 회원가입, 로그인, 토큰 발급, 인증 인가 기능 구현
  itty-backend/build.gradle
  itty-backend/src/main/java/org/iot/itty/login/jwt/JwtFilter.java
  itty-backend/src/main/java/org/iot/itty/login/jwt/JwtUtil.java
  itty-backend/src/main/java/org/iot/itty/login/security/AuthenticationFilter.java
  itty-backend/src/main/java/org/iot/itty/login/security/WebSecurityConfig.java
  itty-backend/src/main/java/org/iot/itty/login/service/LoginService.java
  itty-backend/src/main/java/org/iot/itty/login/service/LoginServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/login/vo/RequestRegist.java
  itty-backend/src/main/java/org/iot/itty/user/repository/UserRepository.java
  itty-backend/src/main/resources/application.yml
  itty-backend/src/test/java/org/iot/itty/login/controller/LoginControllerTests.java
Labels: enhancement

#64 Feat: "selectAllArticleByUserCodeFk test 코드 구현"
  itty-backend/src/test/java/org/iot/itty/article/controller/ArticleControllerTests.java
Labels: enhancement

#67 [Feature] 회원 탈퇴 기능 구현 완료
  itty-backend/src/main/java/org/iot/itty/login/controller/LoginController.java
  itty-backend/src/main/java/org/iot/itty/login/security/AuthenticationFilter.java
  itty-backend/src/main/java/org/iot/itty/login/service/LoginService.java
  itty-backend/src/main/java/org/iot/itty/login/service/LoginServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/login/vo/RequestWithdrawal.java
  itty-backend/src/main/java/org/iot/itty/login/vo/ResponseWithdrawal.java
Labels: enhancement

#69 [Feat] 팔로워 조회, 팔로잉 조회, 팔로잉 추가 구현 완료
  itty-backend/src/main/java/org/iot/itty/dto/FollowDTO.java
  itty-backend/src/main/java/org/iot/itty/user/aggregate/FollowEntity.java
  itty-backend/src/main/java/org/iot/itty/user/controller/FollowController.java
  itty-backend/src/main/java/org/iot/itty/user/repository/FollowRepository.java
  itty-backend/src/main/java/org/iot/itty/user/service/FollowService.java
  itty-backend/src/main/java/org/iot/itty/user/service/FollowServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/user/service/UserService.java
  itty-backend/src/main/java/org/iot/itty/user/service/UserServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseFollow.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseFollower.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseFollowing.java
Labels: enhancement

#72 [Integration] user 도메인 코드 중간 통합
  .idea/.name
  itty-backend/build.gradle
  itty-backend/src/main/java/org/iot/itty/config/ElasticSearchConfig.java
  itty-backend/src/main/java/org/iot/itty/dto/FollowDTO.java
  itty-backend/src/main/java/org/iot/itty/user/aggregate/FollowEntity.java
  itty-backend/src/main/java/org/iot/itty/user/controller/FollowController.java
  itty-backend/src/main/java/org/iot/itty/user/repository/FollowRepository.java
  itty-backend/src/main/java/org/iot/itty/user/service/FollowService.java
  itty-backend/src/main/java/org/iot/itty/user/service/FollowServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/user/service/UserService.java
  itty-backend/src/main/java/org/iot/itty/user/service/UserServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseFollow.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseFollower.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseFollowing.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseUnFollow.java
Labels: enhancement

#81 [Feature] 댓글 CRUD, 좋아요(게시글/댓글) CRUD 완료
  itty-backend/build.gradle
  itty-backend/src/main/java/org/iot/itty/article/aggregate/ArticleLikeEntity.java
  itty-backend/src/main/java/org/iot/itty/article/aggregate/CrawledArticle.java
  itty-backend/src/main/java/org/iot/itty/article/aggregate/ReplyLikeEntity.java
  itty-backend/src/main/java/org/iot/itty/article/aggregate/TrendArticleEntity.java
  itty-backend/src/main/java/org/iot/itty/article/controller/CrawlingController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/LikeController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/ReplyController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/TrendArticleController.java
  itty-backend/src/main/java/org/iot/itty/article/repository/ArticleLikeRepository.java
  itty-backend/src/main/java/org/iot/itty/article/repository/LikeRepository.java
  itty-backend/src/main/java/org/iot/itty/article/repository/ReplyLikeRepository.java
  itty-backend/src/main/java/org/iot/itty/article/repository/TrendArticleRepository.java
  itty-backend/src/main/java/org/iot/itty/article/service/CrawlingService.java
  itty-backend/src/main/java/org/iot/itty/article/service/CrawlingServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/service/LikeService.java
  itty-backend/src/main/java/org/iot/itty/article/service/LikeServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/service/ReplyService.java
  itty-backend/src/main/java/org/iot/itty/article/service/ReplyServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/service/TrendArticleService.java
  itty-backend/src/main/java/org/iot/itty/article/service/TrendArticleServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestAddArticleLike.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestAddReplyLike.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestDeleteArticleLike.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestDeleteReplyLike.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestModifyReply.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseModifyReply.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseSelectAllArticleLikedByUserCodeFk.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseTrendArticle.java
  itty-backend/src/main/java/org/iot/itty/config/ElasticSearchConfig.java
  itty-backend/src/main/java/org/iot/itty/dto/ArticleLikeDTO.java
  itty-backend/src/main/java/org/iot/itty/dto/ReplyLikeDTO.java
  itty-backend/src/main/java/org/iot/itty/dto/TrendArticleDTO.java
  itty-backend/src/main/java/org/iot/itty/dto/UserDTO.java
  itty-backend/src/main/java/org/iot/itty/user/controller/UserController.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseSelectUserByUserCodePk.java
  itty-backend/src/main/resources/application.yml
Labels: enhancement

#82 [Merge] 댓글, 좋아요 CRUD 완료 이후 중간 통합
  itty-backend/build.gradle
  itty-backend/src/main/java/org/iot/itty/article/aggregate/ArticleLikeEntity.java
  itty-backend/src/main/java/org/iot/itty/article/aggregate/CrawledArticle.java
  itty-backend/src/main/java/org/iot/itty/article/aggregate/ReplyLikeEntity.java
  itty-backend/src/main/java/org/iot/itty/article/aggregate/TrendArticleEntity.java
  itty-backend/src/main/java/org/iot/itty/article/controller/CrawlingController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/LikeController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/ReplyController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/TrendArticleController.java
  itty-backend/src/main/java/org/iot/itty/article/repository/ArticleLikeRepository.java
  itty-backend/src/main/java/org/iot/itty/article/repository/LikeRepository.java
  itty-backend/src/main/java/org/iot/itty/article/repository/ReplyLikeRepository.java
  itty-backend/src/main/java/org/iot/itty/article/repository/TrendArticleRepository.java
  itty-backend/src/main/java/org/iot/itty/article/service/CrawlingService.java
  itty-backend/src/main/java/org/iot/itty/article/service/CrawlingServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/service/LikeService.java
  itty-backend/src/main/java/org/iot/itty/article/service/LikeServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/service/ReplyService.java
  itty-backend/src/main/java/org/iot/itty/article/service/ReplyServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/service/TrendArticleService.java
  itty-backend/src/main/java/org/iot/itty/article/service/TrendArticleServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestAddArticleLike.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestAddReplyLike.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestDeleteArticleLike.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestDeleteReplyLike.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestModifyReply.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseModifyReply.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseSelectAllArticleLikedByUserCodeFk.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseTrendArticle.java
  itty-backend/src/main/java/org/iot/itty/config/ElasticSearchConfig.java
  itty-backend/src/main/java/org/iot/itty/dto/ArticleLikeDTO.java
  itty-backend/src/main/java/org/iot/itty/dto/ReplyLikeDTO.java
  itty-backend/src/main/java/org/iot/itty/dto/TrendArticleDTO.java
  itty-backend/src/main/java/org/iot/itty/dto/UserDTO.java
  itty-backend/src/main/java/org/iot/itty/user/controller/UserController.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseSelectUserByUserCodePk.java
  itty-backend/src/main/resources/application.yml
Labels: enhancement

#83 [Feat] 트렌드 게시글 스크랩 CRUD 완료
  itty-backend/src/main/java/org/iot/itty/article/aggregate/CrawledArticle.java
  itty-backend/src/main/java/org/iot/itty/article/aggregate/ScrapEntity.java
  itty-backend/src/main/java/org/iot/itty/article/controller/CrawlingController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/ScrapController.java
  itty-backend/src/main/java/org/iot/itty/article/repository/ScrapRepository.java
  itty-backend/src/main/java/org/iot/itty/article/service/CrawlingService.java
  itty-backend/src/main/java/org/iot/itty/article/service/CrawlingServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/service/ScrapService.java
  itty-backend/src/main/java/org/iot/itty/article/service/ScrapServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestAddScrap.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestDeleteScrap.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseSelectAllScrapByUserCodeFk.java
  itty-backend/src/main/java/org/iot/itty/dto/ScrapDTO.java
Labels: enhancement

#84 [Merge] 스크랩 CRUD 구현 완료 후 중간 통합
  itty-backend/src/main/java/org/iot/itty/article/aggregate/CrawledArticle.java
  itty-backend/src/main/java/org/iot/itty/article/aggregate/ScrapEntity.java
  itty-backend/src/main/java/org/iot/itty/article/controller/CrawlingController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/ScrapController.java
  itty-backend/src/main/java/org/iot/itty/article/repository/ScrapRepository.java
  itty-backend/src/main/java/org/iot/itty/article/service/CrawlingService.java
  itty-backend/src/main/java/org/iot/itty/article/service/CrawlingServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/service/ScrapService.java
  itty-backend/src/main/java/org/iot/itty/article/service/ScrapServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestAddScrap.java
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestDeleteScrap.java
  itty-backend/src/main/java/org/iot/itty/article/vo/ResponseSelectAllScrapByUserCodeFk.java
  itty-backend/src/main/java/org/iot/itty/dto/ScrapDTO.java
Labels: enhancement

#85 [Feat] 트렌드 게시글 삭제 / 회원 프로필 조회 시 스크랩 게시글 조회 완료
  itty-backend/src/main/java/org/iot/itty/article/controller/TrendArticleController.java
  itty-backend/src/main/java/org/iot/itty/article/service/TrendArticleService.java
  itty-backend/src/main/java/org/iot/itty/article/service/TrendArticleServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/dto/UserDTO.java
  itty-backend/src/main/java/org/iot/itty/user/controller/UserController.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseSelectUserByUserCodePk.java
Labels: enhancement

#86 [Merge] 스크랩 기능 구현 완료 이후 중간 통합
  itty-backend/src/main/java/org/iot/itty/article/controller/TrendArticleController.java
  itty-backend/src/main/java/org/iot/itty/article/service/TrendArticleService.java
  itty-backend/src/main/java/org/iot/itty/article/service/TrendArticleServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/dto/UserDTO.java
  itty-backend/src/main/java/org/iot/itty/user/controller/UserController.java
  itty-backend/src/main/java/org/iot/itty/user/vo/ResponseSelectUserByUserCodePk.java
Labels: enhancement

#88 [Merge] 회원가입, 로그인, 로그아웃, 회원탈퇴 기능 구현 완료 후 중간 통합
  itty-backend/build.gradle
  itty-backend/src/main/java/org/iot/itty/dto/TokenDTO.java
  itty-backend/src/main/java/org/iot/itty/login/controller/LoginController.java
  itty-backend/src/main/java/org/iot/itty/login/exception/BlackToken.java
  itty-backend/src/main/java/org/iot/itty/login/exception/InputNotFoundException.java
  itty-backend/src/main/java/org/iot/itty/login/exception/InvalidToken.java
  itty-backend/src/main/java/org/iot/itty/login/exception/NotExistingToken.java
  itty-backend/src/main/java/org/iot/itty/login/exception/TokenExpiredException.java
  itty-backend/src/main/java/org/iot/itty/login/jwt/JwtFilter.java
  itty-backend/src/main/java/org/iot/itty/login/jwt/JwtUtil.java
  itty-backend/src/main/java/org/iot/itty/login/redis/BlackToken.java
  itty-backend/src/main/java/org/iot/itty/login/redis/BlackTokenRepository.java
  itty-backend/src/main/java/org/iot/itty/login/redis/RedisConfig.java
  itty-backend/src/main/java/org/iot/itty/login/redis/RefreshToken.java
  itty-backend/src/main/java/org/iot/itty/login/redis/RefreshTokenService.java
  itty-backend/src/main/java/org/iot/itty/login/redis/TokenRepository.java
  itty-backend/src/main/java/org/iot/itty/login/security/AuthenticationFilter.java
  itty-backend/src/main/java/org/iot/itty/login/security/TokenGenerator.java
  itty-backend/src/main/java/org/iot/itty/login/security/UserLogoutHandler.java
  itty-backend/src/main/java/org/iot/itty/login/security/WebSecurityConfig.java
  itty-backend/src/main/java/org/iot/itty/login/service/LoginService.java
  itty-backend/src/main/java/org/iot/itty/login/service/LoginServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/login/vo/RequestWithdrawal.java
  itty-backend/src/main/java/org/iot/itty/login/vo/ResponseToken.java
  itty-backend/src/main/java/org/iot/itty/login/vo/ResponseWithdrawal.java
  itty-backend/src/main/resources/application.yml
  itty-backend/src/test/java/org/iot/itty/login/redis/RedisCacheTests.java
Labels: enhancement

#89 [Merge] 프로메테우스, jsoup 의존성 추가
  itty-backend/build.gradle
  itty-backend/src/main/java/org/iot/itty/login/controller/LoginController.java
  itty-backend/src/main/resources/application.yml
Labels: refactor

#90 [Refactor] RESTful한 API로 리팩토링
  itty-backend/src/main/java/org/iot/itty/article/controller/ArticleController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/LikeController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/ReplyController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/ScrapController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/TrendArticleController.java
  itty-backend/src/main/java/org/iot/itty/user/controller/FollowController.java
Labels: enhancement

#91 [Merge] API 리팩토링 이후 중간 통합
  itty-backend/src/main/java/org/iot/itty/article/controller/ArticleController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/LikeController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/ReplyController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/ScrapController.java
  itty-backend/src/main/java/org/iot/itty/article/controller/TrendArticleController.java
  itty-backend/src/main/java/org/iot/itty/user/controller/FollowController.java
Labels: enhancement

#93 [Feat] 회원 탈퇴 시 비밀번호 유효성 검사 기능 추가
  itty-backend/src/main/java/org/iot/itty/login/controller/LoginController.java
  itty-backend/src/main/java/org/iot/itty/login/service/LoginService.java
  itty-backend/src/main/java/org/iot/itty/login/service/LoginServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/login/vo/RequestWithdrawal.java
Labels: enhancement

#94 [Merge] 회원 탈퇴 시 비밀번호 유효성 검사 기능 구현 완료 후 중간 통합
  itty-backend/build.gradle
  itty-backend/src/main/java/org/iot/itty/login/controller/LoginController.java
  itty-backend/src/main/java/org/iot/itty/login/service/LoginService.java
  itty-backend/src/main/java/org/iot/itty/login/service/LoginServiceImpl.java
  itty-backend/src/main/java/org/iot/itty/login/vo/RequestWithdrawal.java
  itty-backend/src/main/resources/application.yml
Labels: enhancement

#98 Fix: "메인 머지 오류 수정"
  itty-backend/src/main/java/org/iot/itty/article/vo/RequestRegistFreeBoardArticle.java
Labels: enhancement

#108 [Test] 좋아요 관련 테스트 작성
  build.gradle
  daemon/8.7/registry.bin
  daemon/8.7/registry.bin.lock
  src/main/java/org/iot/itty/article/controller/LikeController.java
  src/main/java/org/iot/itty/article/vo/RequestAddArticleLike.java
  src/main/java/org/iot/itty/article/vo/RequestAddReplyLike.java
  src/main/java/org/iot/itty/article/vo/RequestDeleteArticleLike.java
  src/main/java/org/iot/itty/article/vo/RequestDeleteBulletinArticle.java
  src/main/java/org/iot/itty/article/vo/RequestDeleteReplyLike.java
  src/main/java/org/iot/itty/article/vo/RequestModifyFreeBoardArticle.java
  src/main/java/org/iot/itty/article/vo/RequestRegistFreeBoardArticle.java
  src/main/resources/application.yml
  src/test/java/org/iot/itty/article/controller/ArticleControllerTests.java
  src/test/java/org/iot/itty/article/controller/LikeControllerTest.java
Labels: enhancement, test

#109 [Feat] 회원 가입 닉네임 중복 검사 기능 추가
  src/main/java/org/iot/itty/login/controller/LoginController.java
  src/main/java/org/iot/itty/login/service/LoginService.java
  src/main/java/org/iot/itty/login/service/LoginServiceImpl.java
  src/main/java/org/iot/itty/login/vo/ResponseRegist.java
  src/main/java/org/iot/itty/user/repository/UserRepository.java
  src/test/java/org/iot/itty/login/controller/LoginControllerTests.java
Labels: enhancement, test

#110 [Test] 게시글 테스트코드 작성 및 수정 완료
  src/main/java/org/iot/itty/article/controller/ArticleController.java
  src/test/java/org/iot/itty/article/controller/ArticleControllerTests.java
Labels: enhancement

#111 [Test] 회원 가입 및 회원 탈퇴 테스트 코드 작성 완료
  src/main/resources/application.yml
  src/test/java/org/iot/itty/login/controller/LoginControllerTests.java
Labels: test

#112 [Test] 댓글 테스트 구현
  daemon/8.7/registry.bin
  daemon/8.7/registry.bin.lock
  src/main/java/org/iot/itty/article/controller/ReplyController.java
  src/main/java/org/iot/itty/article/service/ReplyServiceImpl.java
  src/main/java/org/iot/itty/article/vo/RequestDeleteReply.java
  src/main/java/org/iot/itty/article/vo/RequestModifyReply.java
  src/main/java/org/iot/itty/article/vo/RequestRegistReply.java
  src/test/java/org/iot/itty/article/controller/ReplyControllerTests.java
Labels: enhancement, test
